### ISSUE TITLE
Dice combination issue?

### ISSUE THREAD

**Issue by RichardJThorp** [James-P-D/GeniusSquare#3]
Hi
Thanks for this code.  Ran this and ended up with a duplicate "blocking" location from your dice.  "F2" & "F2".
This resulted in there only being 6 blocking squares on the board.  The game was SOLVED, leaving one BLANK square on the board!  Think there's a little tweaking required in either your dice combinations or the dice "throwing" routine.
![Screenshot 2021-12-29 151017](https://user-images.githubusercontent.com/96832983/147676773-b39d4649-75c5-4d53-810e-463186fb7155.png)

Not being a programmer, I doubt I'd have any clue as to what the issue is, but just thought you might like to know.
Thanks again for a great program to compliment my addiction to THE GENIUS SQUARE.
Regards, Richard.

**Comment by James-P-D** [comment]
Hiya, thanks for getting in touch. It looks like I've transcribed the values for the dice incorrectly. (Over in https://github.com/James-P-D/GeniusSquare/blob/master/src/GeniusSquare/GeniusSquare/Constants.py it looks like F2, which is encoded as (1, 5), appears in both the first and second row, meaning that both the first and second dice can roll it.)

I don't have the game to hand right now, but I'll try and find what the correct dice combinations are and update when I get a chance.

**Comment by RichardJThorp** [comment]
Hi James,
Yes, I came to the same conclusion.  F2 is on dice #1 and #2.  I have the game and have checked the physical dice.
The F2 on dice #1 should be F3 - A1 C1 D1 D2 E2 F3 - so where you have coded [1,5] "F2" should be [2,5] "F3".
Regards, Richard

**Comment by James-P-D** [comment]
Many thanks, @RichardJThorp ! I've updated the program.
Kind regards, and hope you have a good xmas/new year

**Comment by RichardJThorp** [comment]
Thanks James.  Have a good Christmas/New Year also.  Richard.
